# Copyright (C) 2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/lt02wifi-common/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/lt02wifi-common/proprietary/bin/amixer:system/bin/amixer \
    vendor/samsung/lt02wifi-common/proprietary/bin/aplay:system/bin/aplay \
    vendor/samsung/lt02wifi-common/proprietary/bin/appCoda7542Dec:system/bin/appCoda7542Dec \
    vendor/samsung/lt02wifi-common/proprietary/bin/appCoda7542Enc:system/bin/appCoda7542Enc \
    vendor/samsung/lt02wifi-common/proprietary/bin/cploader:system/bin/cploader \
    vendor/samsung/lt02wifi-common/proprietary/bin/emmc_fsck:system/bin/emmc_fsck \
    vendor/samsung/lt02wifi-common/proprietary/bin/hwacc:system/bin/hwacc \
    vendor/samsung/lt02wifi-common/proprietary/bin/i2cdetect:system/bin/i2cdetect \
    vendor/samsung/lt02wifi-common/proprietary/bin/i2cdump:system/bin/i2cdump \
    vendor/samsung/lt02wifi-common/proprietary/bin/i2cget:system/bin/i2cget \
    vendor/samsung/lt02wifi-common/proprietary/bin/i2cset:system/bin/i2cset \
    vendor/samsung/lt02wifi-common/proprietary/bin/MarvellWirelessDaemon:system/bin/MarvellWirelessDaemon \
    vendor/samsung/lt02wifi-common/proprietary/bin/mlanutl:system/bin/mlanutl \
    vendor/samsung/lt02wifi-common/proprietary/bin/mrvl_dut:system/bin/mrvl_dut \
    vendor/samsung/lt02wifi-common/proprietary/bin/msocket_testport:system/bin/msocket_testport \
    vendor/samsung/lt02wifi-common/proprietary/bin/pand:system/bin/pand \
    vendor/samsung/lt02wifi-common/proprietary/bin/ppd_cmd:system/bin/ppd_cmd \
    vendor/samsung/lt02wifi-common/proprietary/bin/sensord:system/bin/sensord \
    vendor/samsung/lt02wifi-common/proprietary/bin/serial_cfun0:system/bin/serial_cfun0 \
    vendor/samsung/lt02wifi-common/proprietary/bin/serial_client:system/bin/serial_client \
    vendor/samsung/lt02wifi-common/proprietary/bin/serial_client_test:system/bin/serial_client_test \
    vendor/samsung/lt02wifi-common/proprietary/bin/usr_path_ctrl:system/bin/usr_path_ctrl \
    vendor/samsung/lt02wifi-common/proprietary/bin/vcm:system/bin/vcm \
    vendor/samsung/lt02wifi-common/proprietary/bin/vt_test:system/bin/vt_test \
    vendor/samsung/lt02wifi-common/proprietary/lib/egl/libGLES_android.so:system/lib/egl/libGLES_android.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/egl/libEGL_MRVL.so:system/lib/egl/libEGL_MRVL.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/egl/libGLESv1_CM_MRVL.so:system/lib/egl/libGLESv1_CM_MRVL.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/egl/libGLESv2_MRVL.so:system/lib/egl/libGLESv2_MRVL.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libGAL.so:system/lib/libGAL.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/hw/audio.primary.mrvl.so:system/lib/hw/audio.primary.mrvl.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/hw/audio_path.adda.mrvl.so:system/lib/hw/audio_path.adda.mrvl.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/hw/audio_path.fm.mrvl.so:system/lib/hw/audio_path.fm.mrvl.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/hw/audio_path.hifi.mrvl.so:system/lib/hw/audio_path.hifi.mrvl.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/hw/audio_path.vc.mrvl.so:system/lib/hw/audio_path.vc.mrvl.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/hw/audio_path.voip.mrvl.so:system/lib/hw/audio_path.voip.mrvl.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/hw/audio_path.vt.mrvl.so:system/lib/hw/audio_path.vt.mrvl.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/hw/audio_policy.mrvl.so:system/lib/hw/audio_policy.mrvl.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libacoustic.so:system/lib/libacoustic.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libaudiodebugtool.so:system/lib/libaudiodebugtool.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libMarvellWireless.so:system/lib/libMarvellWireless.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libaudiosa.so:system/lib/libaudiosa.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/liblvvewrapper.so:system/lib/liblvvewrapper.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libmarvell-nvaccessor.so:system/lib/libmarvell-nvaccessor.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libmarvell-ril.so:system/lib/libmarvell-ril.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libMarvellWireless.so:system/lib/libMarvellWireless.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libmiscgen.so:system/lib/libmiscgen.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libMrvlOmx.so:system/lib/libMrvlOmx.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libnvaccessor.so:system/lib/libnvaccessor.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libmtelif.so:system/lib/libmtelif.so \
    vendor/samsung/lt02wifi-common/proprietary/cameradata/datapattern_420sp.yuv:system/cameradata/datapattern_420sp.yuv \
    vendor/samsung/lt02wifi-common/proprietary/cameradata/datapattern_front_420sp.yuv:system/cameradata/datapattern_front_420sp.yuv \
    vendor/samsung/lt02wifi-common/proprietary/lib/hw/camera.mrvl.so:system/lib/hw/camera.mrvl.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libcameraengine.so:system/lib/libcameraengine.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libcodecjpegdec.so:system/lib/libcodecjpegdec.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libcodecjpegenc.so:system/lib/libcodecjpegenc.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libmiscgen.so:system/lib/libmiscgen.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libphycontmem.so:system/lib/libphycontmem.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libsocketsvr.so:system/lib/libsocketsvr.so \
    vendor/samsung/lt02wifi-common/proprietary/etc/ov5647_scene_tuning.data:system/etc/ov5647_scene_tuning.data \
    vendor/samsung/lt02wifi-common/proprietary/lib/libcoda7542hal.so:system/lib/libcoda7542hal.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libcoda7542.so:system/lib/libcoda7542.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libcodecaacdec.so:system/lib/libcodecaacdec.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libcodecaacenc.so:system/lib/libcodecaacenc.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libcodecamrnbdec.so:system/lib/libcodecamrnbdec.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libcodecamrnbenc.so:system/lib/libcodecamrnbenc.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libcodecamrwbdec.so:system/lib/libcodecamrwbdec.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libcodecamrwbenc.so:system/lib/libcodecamrwbenc.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libcodeccoda7542dec.so:system/lib/libcodeccoda7542dec.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libcodeccoda7542enc.so:system/lib/libcodeccoda7542enc.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libcodech263dec.so:system/lib/libcodech263dec.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libcodech263enc.so:system/lib/libcodech263enc.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libcodech264dec.so:system/lib/libcodech264dec.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libcodech264enc.so:system/lib/libcodech264enc.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libcodecjpegdec.so:system/lib/libcodecjpegdec.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libcodecjpegenc.so:system/lib/libcodecjpegenc.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libcodecmp3dec.so:system/lib/libcodecmp3dec.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libcodecmpeg2dec.so:system/lib/libcodecmpeg2dec.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libcodecmpeg4dec.so:system/lib/libcodecmpeg4dec.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libcodecmpeg4enc.so:system/lib/libcodecmpeg4enc.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libcodecpngdec.so:system/lib/libcodecpngdec.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libcodecwmadec.so:system/lib/libcodecwmadec.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libcodecwmvdec.so:system/lib/libcodecwmvdec.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libffmpeg.so:system/lib/libffmpeg.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/hw/sensors.mrvl.so:system/lib/hw/sensors.mrvl.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libcpufreqinterface.so:system/lib/libcpufreqinterface.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libcpufreq.so:system/lib/libcpufreq.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    vendor/samsung/lt02wifi-common/proprietary/etc/AGPS_CA.pem:system/etc/AGPS_CA.pem \
    vendor/samsung/lt02wifi-common/proprietary/lib/hw/csr.cpd.so:system/lib/hw/csr.cpd.so \
    vendor/samsung/lt02wifi-common/proprietary/etc/firmware/mrvl/reg_alpha2:system/etc/firmware/mrvl/reg_alpha2 \
    vendor/samsung/lt02wifi-common/proprietary/etc/firmware/mrvl/sd8787_uapsta.bin:system/etc/firmware/mrvl/sd8787_uapsta.bin \
    vendor/samsung/lt02wifi-common/proprietary/etc/firmware/mrvl/txpwrlimit_cfg.conf:system/etc/firmware/mrvl/txpwrlimit_cfg.conf \
    vendor/samsung/lt02wifi-common/proprietary/etc/firmware/mrvl/w8787_wlan_SDIO_bt_SDIO.bin:system/etc/firmware/mrvl/w8787_wlan_SDIO_bt_SDIO.bin \
    vendor/samsung/lt02wifi-common/proprietary/etc/firmware/mrvl/WlanCalData_ext.conf:system/etc/firmware/mrvl/WlanCalData_ext.conf \
    vendor/samsung/lt02wifi-common/proprietary/etc/firmware/mrvl/WlanCalData_ext.conf_0:system/etc/firmware/mrvl/WlanCalData_ext.conf_0 \
    vendor/samsung/lt02wifi-common/proprietary/lib/libwtpsp.so:system/lib/libwtpsp.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libwtpsp_ss.so:system/lib/libwtpsp_ss.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libwtpsp.so:system/lib/libwtpsp.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libwtpsp_ss.so:system/lib/libwtpsp_ss.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libusbsetting.so:system/lib/libusbsetting.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libsysfs.so:system/lib/libsysfs.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libsraxxd.so:system/lib/libsraxxd.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libsrvxxd.so:system/lib/libsrvxxd.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libsimal.so:system/lib/libsimal.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libserialport.so:system/lib/libserialport.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libceu.so:system/lib/libceu.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libCSP.so:system/lib/libCSP.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libgcu.so:system/lib/libgcu.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libgpucsc.so:system/lib/libgpucsc.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/lib_gsd5t_mode7.so:system/lib/lib_gsd5t_mode7.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libbz.so:system/lib/libbz.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libaah_rtp.so:system/lib/libaah_rtp.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libacm.so:system/lib/libacm.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libAndroidEvent.so:system/lib/libAndroidEvent.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libHSV.so:system/lib/libHSV.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libHWComposerGC.so:system/lib/libHWComposerGC.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libionhelper.so:system/lib/libionhelper.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libippimgp.so:system/lib/libippimgp.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libippsp.so:system/lib/libippsp.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libippvp.so:system/lib/libippvp.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libOrgan.so:system/lib/libOrgan.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libpmemhelper.so:system/lib/libpmemhelper.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libPowerSetting.so:system/lib/libPowerSetting.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libparseTim.so:system/lib/libparseTim.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libSDRMInvLH.so:system/lib/libSDRMInvLH.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/hw/lights.mrvl.so:system/lib/hw/lights.mrvl.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/hw/gralloc.mrvl.so:system/lib/hw/gralloc.mrvl.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/hw/hwcomposer.mrvl.so:system/lib/hw/hwcomposer.mrvl.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libHWComposerGC.so:system/lib/libHWComposerGC.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libgcu.so:system/lib/libgcu.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libdivxdrm.so:system/lib/libdivxdrm.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/drm/libdrmwvmplugin.so:system/lib/drm/libdrmwvmplugin.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libWVStreamControlAPI_L3.so:system/lib/libWVStreamControlAPI_L3.so \
    vendor/samsung/lt02wifi-common/proprietary/lib/libwvdrm_L3.so:system/lib/libwvdrm_L3.so
